In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.8.0


In [2]:
mnist = tf.keras.datasets.mnist

In [3]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11501568/11490434 [==============================] - 2s 0us/step


In [4]:
x_train, x_test = x_train / 255.0, x_test / 255.0

In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.19962831, -0.6350766 ,  0.2514156 , -0.36109763,  0.08626856,
         0.35977715, -0.05957319,  0.5317164 , -0.04760195, -0.49411187]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.08139531, 0.05266069, 0.12778658, 0.06925867, 0.10833349,
        0.14241183, 0.09363205, 0.16912909, 0.09475967, 0.06063268]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()

1.9490323

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 12s 5ms/step - loss: 0.2983 - accuracy: 0.9122
Epoch 2/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1413 - accuracy: 0.9581
Epoch 3/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.1071 - accuracy: 0.9668
Epoch 4/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.0859 - accuracy: 0.9735
Epoch 5/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0732 - accuracy: 0.9772


In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.6888845e-08, 5.8882677e-10, 2.2985566e-06, 3.2032054e-05,
        9.4249339e-12, 2.5162588e-09, 6.7798127e-13, 9.9996424e-01,
        1.0776288e-07, 1.2175906e-06],
       [7.3776709e-09, 9.6105723e-06, 9.9998271e-01, 7.5693602e-06,
        4.4819983e-14, 4.7125321e-09, 5.2036371e-09, 9.4660486e-14,
        7.3019933e-08, 6.9951062e-16],
       [8.6009140e-07, 9.9835569e-01, 8.8845642e-05, 1.5092440e-06,
        3.5914552e-05, 1.3698715e-07, 2.4930353e-06, 1.5030405e-03,
        1.0109918e-05, 1.4521499e-06],
       [9.9951720e-01, 1.3379243e-09, 2.8631688e-04, 1.9868805e-06,
        5.5573969e-07, 2.0039197e-06, 1.3579437e-04, 5.6277636e-06,
        3.8120882e-06, 4.6624773e-05],
       [1.2214926e-05, 5.0549826e-08, 2.6915131e-06, 2.0784540e-08,
        9.9512523e-01, 4.3777774e-08, 6.5654149e-06, 1.1656748e-04,
        2.1779870e-06, 4.7343583e-03]], dtype=float32)>